### ISSUE TITLE
vapid key generation & licence

### ISSUE THREAD

**Issue by abhisheksahani** [lahiiru/browser-push#1]
like gcm , is the license required for vapid also if we try to send data more than 25K per day

**Comment by lahiiru** [comment]
Chrome and Opera uses FCM for web push notification delivery. FCM limitations applies. Further, it is totally free and no special limitations. https://firebase.google.com/pricing/ Am I answered your question?

**Comment by abhisheksahani** [comment]
my question is i am using vapid keys in my server for web push notification and  how this vapid keys are generated. if i go to FCM website  i can see only my Server key and Sender ID .

**Comment by lahiiru** [comment]
# What is VAPID
**VAPID** stands for Voluntary Application Server Identification. It is a mechanism whereby an application server can volunteer information about itself to a push service. At a minimum, this provides a **stable identity** for the application server, though this could also include contact information, such as an email address.

# Why VAPID?
**Stable identity** is provided by a key pair. Therefore, application servers **(Not Google)** should generate and maintain a signing key pair usable with elliptic curve digital signature (ECDSA) over the P-256 curve. Use of this key when sending push messages establishes a continuous identity for the application server. Voluntarily-provided contact information can be used to contact an application server operator in the case of exceptional situations.

# How key pairs generated?
It is mathematics. If you know elliptic curves, you can write your own algorithm. Otherwise, you can use `front-end/keygen.html` (Have you read section 1.1 in https://lahiiru.github.io/browser-push/ documentation). For the source code [server-key-generator.js](https://github.com/lahiiru/browser-push/blob/master/front-end/server-key-generator.js) uses javascript inbuilt functions to calculate a key pair.

Finally,  did you found what you want?
