### ISSUE TITLE
getting 400 for chrome same is working on mozilla

### ISSUE THREAD

**Issue by abhisheksahani** [lahiiru/browser-push#2]
hi i am getting two different subscription object for chrome and mozila

for chrome:
{
  "endpoint": "https://fcm.googleapis.com/fcm/send/cp6K0Ufqlfo:APA91bGpukqdUgmZEmDahqVcx8f…A-aX1OJLchLsrXtSAwzuq0wZzTux_tKGvbqNyQ1TrV79Z-NwwxW7BfIZQd8bsGV_pdPCn5xUOD",
  "keys": {
    "p256dh": "BLFlgFarRcRgt3zXbrP5LdmVfsL-QiodUIdcAIdScFF3kI3PoPWcru68lRpcN3WDyx47LOmCPwCUPbgmAqJqHKk=",
    "auth": "Xvc64Extsq51hnIIFxfqsg=="
  }
}

for mozilla:
{
  "endpoint": "https://updates.push.services.mozilla.com/wpush/v1/gAAAAABYjzN0O5fiP10VARKXLu1hqMX7Uxu5qNAbM6a3fijF3ioU7lEOCVL1QcYvrk5DsOdC-lj_XkHm9_ylWmz70Dkld1hwUUrorYSUje1nMsZdYMcgL0dZTh1MecyIrOW7poIUf8Wo",
  "keys": {
    "auth": "11vt9uvVb5iGrilzhqvovQ",
    "p256dh": "BGp9L6pE4w6UuAF4AG-SH7vFN5_WqgQAN6hCo21AZxi8me4vhzaSok6USi2KfTq8pBKtTHeGuOGXwlNAZO3KkzE"
  }
}

as it can be seen in chrome subscription i am getting == sing at end of p256dh and auth but in mozilla i am not getting like this 

and now for chrome it stop working for mozila its working

**Comment by lahiiru** [comment]
How did you copy the subscription string? Don't copy it from developer console. Because, it shows a shorten URLs. Look at Chrome endpoint, It has three dots (...) in middle. Use my debug code (mentioned [here](https://github.com/lahiiru/browser-push/blob/master/README.md)) OR study how I show subscription using an inputbox [here](https://github.com/lahiiru/browser-push/blob/master/front-end/index.html)
However, in your webapp, this subscription string will be forwarded to the application server through a HTTP request.

**Comment by abhisheksahani** [comment]
Yes i was copying from developer console thats why it was not working that time . Thanks
